name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Deploying to EC2
          run: chmod 600 ${{ secrets.EC2_PRIVATE_KEY }} && ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} && 'mkdir -p /tmp/learningdeployment'
