name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Deploying to EC2
          env:
            PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.EC2_HOST}}
            USER_NAME: ${{secrets.EC2_USER}}
          run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              mkdir -p /tmp/demodeployment &&
              cd /tmp/demodeployment &&
              git pull origin main &&
              sudo npm install &&
              sudo node index.js
            '
