name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Deploying to EC2
          env:
            PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.EC2_HOST}}
            USER_NAME: ${{secrets.EC2_USER}}
          run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            echo "$GITHUB_REPOSITORY"
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
              . ~/.nvm/nvm.sh
              nvm install --lts
              rm -rf /home/ubuntu/projects/
              mkdir -p /home/ubuntu/projects
              cd /home/ubuntu/projects
              git clone https://github.com/jitesh1709/learningdeployment.git
              cd learningdeployment
              git pull origin main
              pkill -f node
              echo "Hello"
              npm install
              nohup node index.js
            '
