name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Deploying to EC2
          run: ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ${{secrets.EC2_USERNAME}}@${{ secrets.EC2_HOST }} 'mkdir -p ~/learningdeployment'
